### ISSUE TITLE
[bug]: Cannot create a plugin in Strapi 5

### ISSUE THREAD

**Issue by AleksDrop** [strapi/sdk-plugin#31]
### What's Wrong?

Basic command for creating a plugin fails:
`yarn strapi generate plugin dropdownfield`
yarn run v1.22.22
$ strapi generate plugin dropdownfield
[PLOP] Could not find a generator for "plugin dropdownfield"
error Command failed with exit code 1.

### To Reproduce

- Attempt to create a basic plugin with the following command: `yarn strapi generate plugin dropdownfield`
- Fail with the following error:
`[PLOP] Could not find a generator for "plugin dropdownfield"
error Command failed with exit code 1.`

### Expected Behaviour

One of the following is expected:
* This should work exactly like in Strapi 4
* The docs should be updated to reflect this is not the case
* An alias should be created from the old command to the new

**Comment by AleksDrop** [comment]
https://docs-next.strapi.io/dev-docs/plugins/development/create-a-plugin these docs still mention `yarn strapi generate`

**Comment by hanpaine** [comment]
Hey @AleksDrop thanks for flagging this, it's appreciated! We were indeed talking about this only yesterday. We will most likely be creating an alias for the new command for `yarn strapi generate plugin` and will update the docs too. Thanks again

**Comment by AleksDrop** [comment]
Hi @hanpaine is this closed because it's already implemented? You make it sound like this is only on the todo list.
