### ISSUE TITLE
[feat]: Add Support for Custom Vite Configuration

### ISSUE THREAD

**Issue by Quirkkle** [strapi/sdk-plugin#65]
### A clear and concise description of what the feature is

This feature enables users to create a vite.config.ts file within the plugin/server directory, allowing for the enhancement and customization of the Vite configuration. 

### Why should this feature be included?

By supplementing the default configuration, developers can tailor build options, plugins, and other settings specific to their project needs, facilitating a more flexible development environment.

### Please provide an example for how this would work

`some-plugin/server/vite.config.ts`

``` typescript
import { mergeConfig } from "vite";

export default (config) => {
  return mergeConfig(config, {
    // Vite configuration
  });
};
```

**Comment by Quirkkle** [comment]
I discovered a solution utilizing @strapi/pack-up, which operates under the hood of this tool.

For anyone encountering this issue:

Create a `packup.config.ts` in the root of your plugin

``` typescript
import { defineConfig } from '@strapi/pack-up';

export default defineConfig({
  // Vite configuration
});
```

Then, build your plugin using the following command:

 `npx @strapi/pack-up@latest build`

**Comment by sargreal** [comment]
While it is possible to work around this missing feature, I would really love to have this supported!
